#!/bin/sh


ulimit -c unlimited

export OLDPWD=/config/modules/5.10
export TERMINFO=/config/terminfo
export LD_LIBRARY_PATH=/config/lib:/usr/lib:/root/firmware/app/lib:/root/firmware/media/lib:/root/firmware/app/3dr/lib
export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/config:/root/firmware/app/bin:/root/firmware/app/scripts:/root/firmware/media/bin:/root/firmware/media/scripts:/root/firmware/app/3dr/bin:/root/platform
export EMX_APP_CONFIGS_DIR=/root/firmware/app/configs
export EMX_MEDIA_CONFIGS_DIR=/root/firmware/media/configs
export EMX_DATA_DIR=/root/configs
export APP=/root/firmware/app
export MEDIA=/root/firmware/media

export TMOUT=300

#USER_IP=`who 2>/dev/null| awk '{print $NF}' | awk 'END {print}' | sed 's/\[//g' | sed 's/\]//g' | sed 's/:/_/g' `
USER_IP=`who 2>/dev/null| awk '{print $NF}' | awk 'END {print}'`
result=$(echo $USER_IP | grep "]")
if [ "$result" == "" ]
then
	USER_IP="console"
else
	USER_IP="telnet"
fi


UTMP_NAME="/root/configs/utmp"
if [ -f /root/configs/syslog_ddr_flag ]; then
	UTMP_NAME="/tmp/utmp"
fi

RQ=`date "+%Y%m%d"`
if [ ! -d ${UTMP_NAME}/${USER} ]
then
mkdir -p ${UTMP_NAME}/${USER}
chmod 777 ${UTMP_NAME}
chmod 700 ${UTMP_NAME}/${USER}
fi
export HISTSIZE=1024
export HISTFILESIZE=1024
export HISTTIMEFORMAT='%F %T '
export HISTFILE="${UTMP_NAME}/${USER}/${USER_IP}.log"




