#!/bin/sh
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s && echo "mdev is ok......"

export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/root/firmware/app/bin:/root/firmware/app/scripts:/root/firmware/media/scripts:/root/platform
export LD_LIBRARY_PATH=/lib:/usr/lib:/root/firmware/app/lib:/root/firmware/media/lib


# networking
ifconfig lo 127.0.0.1 up
/root/platform/init.sh

