#include <common.h>
#include <asm/io.h>

/*	HOLD_x
 *	CLK
 *	MOSI
 *	WP_X
 *	MISO
 *	CS
 */

#define SPI_FLASH_IO_CFG_BASE	0x3001900
#define SPI_FLASH_HOLD_X	0x18
#define SPI_FLASH_CLK		0x1c
#define SPI_FLASH_MOSI		0x20
#define SPI_FLASH_WP_X		0x24
#define SPI_FLASH_MISO		0x28
#define	SPI_FLASH_CS		0x2c

#define HOLD_X_PINMUX_VAL	0x8
#define CLK_PINMUX_VAL		0x8
#define MOSI_PINMUX_VAL		0x4
#define WP_X_PINMUX_VAL		0x4
#define MISO_PINMUX_VAL		0x4
#define CS_PINMUX_VAL		0x8

void cvitek_spi_flash_pinmux(void)
{
	writel(HOLD_X_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_HOLD_X));
	writel(CLK_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_CLK));
	writel(MOSI_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_MOSI));
	writel(WP_X_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_WP_X));
	writel(MISO_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_MISO));
	writel(CS_PINMUX_VAL, (SPI_FLASH_IO_CFG_BASE + SPI_FLASH_CS));
}
