ifdef CONFIG_TARGET_CVITEK_CV1835
obj-$(CONFIG_CMD_CVI_UTASK)	:= utask/cv183x/cvi_usb.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv183x/sgdma.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv183x/ss_dev.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv183x/usb_tty.o
endif

ifdef CONFIG_TARGET_CVITEK_CV1822
obj-$(CONFIG_CMD_CVI_UTASK)	:= utask/cv182x/cvi_usb.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv182x/cps_cvi.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv182x/cvi_udc_otg.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv182x/cvi_udc_otg_xfer_dma.o
obj-$(CONFIG_CMD_CVI_UTASK)	+= utask/cv182x/usb_tty.o
endif
